name: chilli
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  pinput: ^5.0.2
  smart_auth: ^2.0.0
#  simple_floating_bottom_nav_bar: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: ArimoBold
      fonts:
        - asset: assets/fonts/Arimo-Bold.ttf
    - family: ArimoMedium
      fonts:
        - asset: assets/fonts/Arimo-Medium.ttf
    - family: ArimoRegular
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
    - family: Avenir LT Pro
      fonts:
        - asset: assets/fonts/AvenirLTProLight.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 500
        - asset: assets/fonts/AvenirLTProBlack.otf
          weight: 800